"""add steward_interest to users

Revision ID: 1b2fdd3d906a
Revises: 1b966eb4c94b
Create Date: 2026-08-16 17:38:28.019675

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b2fdd3d906a"
down_revision: str | Sequence[str] | None = "1b966eb4c94b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "steward_interest", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "steward_interest")
    # ### end Alembic commands ###
