"""drop comments table and notify_on_message

Revision ID: 5b6528441112
Revises: f1e98f0ec3ac
Create Date: 2026-08-15 08:32:11.508952

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b6528441112"
down_revision: str | Sequence[str] | None = "f1e98f0ec3ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# notify_on_message is read by whatever code is still deployed when this migration
# runs. Applying it before the code that stops reading it is live would break those
# still-running instances mid-rollover, so pre-push must let this ship *ahead* of
# a migration, not behind one. See .githooks/pre-push.
post_deploy = True


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_listing_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_column("users", "notify_on_message")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "notify_on_message",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("comments_listing_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("comments_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comments_pkey")),
    )
    op.create_index(op.f("ix_comments_listing_id"), "comments", ["listing_id"], unique=False)
    # ### end Alembic commands ###
