"""add is_seed to listings

Revision ID: 609e77eef42c
Revises: bb6002d33a37
Create Date: 2026-08-15 20:05:30.635221

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '609e77eef42c'
down_revision: str | Sequence[str] | None = 'bb6002d33a37'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_seed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'is_seed')
    # ### end Alembic commands ###
