"""add rate_limit_hits table

Revision ID: 64e3d00636c9
Revises: 5b6528441112
Create Date: 2026-08-15 15:36:46.155435

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64e3d00636c9"
down_revision: str | Sequence[str] | None = "5b6528441112"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_hits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bucket", sa.String(length=20), nullable=False),
        sa.Column("client_key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rate_limit_hits_lookup",
        "rate_limit_hits",
        ["bucket", "client_key", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rate_limit_hits_lookup", table_name="rate_limit_hits")
    op.drop_table("rate_limit_hits")
    # ### end Alembic commands ###
